; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.3.16 on Mon Jul 03 2023 17:00:57 GMT-0400 (Eastern Daylight Time)
M568 P0 A0
M568 P1 A0
M568 P2 A0

; Lower the bed for accessiblity
G91
G0 Z15 F3000
G90

; Deselect the active tool
T-1

; Disable Mesh Compensation.
G29 S2

; Park
G0 Y600
